title: Kunal Mishra | CV
description:  Kunal's CV webpage
baseurl: ''
theme_skin: blue
url: 'https://kunmishra2599.github.io'
sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
