title: Kunal Mishra | CV
description:  Kunal's CV webpage
theme_skin: blue
url: 'https://kunalmishra.me'
sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
