title: Kunal Mishra | CV
description:  Kunal's CV webpage
baseurl: '//kunmishra2599.github.io'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
